name: Gym Tracker CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Check backend
        working-directory: backend
        run: npm run check

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        env:
          VITE_API_URL: https://gym-tracker-52tf.onrender.com/api
        run: npm run build

  docker:
    needs: validate
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/gym-tracker-api:latest \
            ./backend

      - name: Push backend image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/gym-tracker-api:latest

      - name: Build frontend image
        run: |
          docker build \
            --build-arg VITE_API_URL=https://gym-tracker-52tf.onrender.com/api \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/gym-tracker-frontend:latest \
            ./frontend

      - name: Push frontend image
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/gym-tracker-frontend:latest